version: 2
updates:
  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Update npm / pip packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
